// サッカーチームのデータ型
export interface SoccerTeam {
  id: number;
  name: string;
  rank: number;
  points: number;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  logo: string;
}

export const U18A: SoccerTeam[] = [
  {
    id: 1,
    name: "松本国際",
    rank: 1,
    points: 13,
    played: 6,
    won: 4,
    drawn: 1,
    lost: 1,
    goalsFor: 12,
    goalsAgainst: 8,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 2,
    name: "アルビレックス新潟U-18",
    rank: 2,
    points: 13,
    played: 6,
    won: 4,
    drawn: 1,
    lost: 1,
    goalsFor: 8,
    goalsAgainst: 4,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 3,
    name: "鵬学園",
    rank: 3,
    points: 12,
    played: 6,
    won: 4,
    drawn: 0,
    lost: 2,
    goalsFor: 10,
    goalsAgainst: 8,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 4,
    name: "日本文理",
    rank: 4,
    points: 11,
    played: 6,
    won: 3,
    drawn: 2,
    lost: 1,
    goalsFor: 9,
    goalsAgainst: 4,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 5,
    name: "ツエーゲン金沢U-18",
    rank: 5,
    points: 9,
    played: 6,
    won: 3,
    drawn: 0,
    lost: 3,
    goalsFor: 8,
    goalsAgainst: 10,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 6,
    name: "星稜",
    rank: 6,
    points: 8,
    played: 6,
    won: 2,
    drawn: 2,
    lost: 2,
    goalsFor: 6,
    goalsAgainst: 7,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 7,
    name: "松本山雅FC U-18",
    rank: 7,
    points: 6,
    played: 6,
    won: 1,
    drawn: 3,
    lost: 2,
    goalsFor: 7,
    goalsAgainst: 8,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 8,
    name: "新潟明訓",
    rank: 8,
    points: 5,
    played: 6,
    won: 1,
    drawn: 2,
    lost: 3,
    goalsFor: 6,
    goalsAgainst: 7,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 9,
    name: "カターレ富山 U-18",
    rank: 9,
    points: 5,
    played: 6,
    won: 1,
    drawn: 2,
    lost: 3,
    goalsFor: 6,
    goalsAgainst: 8,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 10,
    name: "帝京長岡2nd",
    rank: 10,
    points: 1,
    played: 6,
    won: 0,
    drawn: 1,
    lost: 5,
    goalsFor: 3,
    goalsAgainst: 11,
    logo: "/placeholder.svg?height=24&width=24",
  },
];

export const J3: SoccerTeam[] = [
  {
    id: 1,
    name: "栃木シティ",
    rank: 1,
    points: 25,
    played: 12,
    won: 7,
    drawn: 4,
    lost: 1,
    goalsFor: 19,
    goalsAgainst: 10,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 2,
    name: "テゲバジャーロ宮崎",
    rank: 2,
    points: 22,
    played: 12,
    won: 6,
    drawn: 4,
    lost: 2,
    goalsFor: 16,
    goalsAgainst: 11,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 3,
    name: "ＦＣ大阪",
    rank: 3,
    points: 22,
    played: 11,
    won: 7,
    drawn: 1,
    lost: 3,
    goalsFor: 15,
    goalsAgainst: 10,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 4,
    name: "ヴァンラーレ八戸",
    rank: 4,
    points: 21,
    played: 12,
    won: 6,
    drawn: 3,
    lost: 3,
    goalsFor: 12,
    goalsAgainst: 8,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 5,
    name: "ギラヴァンツ北九州",
    rank: 5,
    points: 20,
    played: 12,
    won: 6,
    drawn: 2,
    lost: 4,
    goalsFor: 12,
    goalsAgainst: 7,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 6,
    name: "奈良クラブ",
    rank: 6,
    points: 19,
    played: 12,
    won: 5,
    drawn: 4,
    lost: 3,
    goalsFor: 16,
    goalsAgainst: 14,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 7,
    name: "福島ユナイテッドＦＣ",
    rank: 7,
    points: 18,
    played: 12,
    won: 5,
    drawn: 3,
    lost: 4,
    goalsFor: 22,
    goalsAgainst: 22,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 8,
    name: "鹿児島ユナイテッドＦＣ",
    rank: 8,
    points: 17,
    played: 11,
    won: 4,
    drawn: 5,
    lost: 2,
    goalsFor: 18,
    goalsAgainst: 12,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 9,
    name: "ツエーゲン金沢",
    rank: 9,
    points: 17,
    played: 12,
    won: 5,
    drawn: 2,
    lost: 5,
    goalsFor: 14,
    goalsAgainst: 14,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 10,
    name: "松本山雅ＦＣ",
    rank: 10,
    points: 15,
    played: 10,
    won: 4,
    drawn: 3,
    lost: 3,
    goalsFor: 11,
    goalsAgainst: 12,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 11,
    name: "栃木ＳＣ",
    rank: 11,
    points: 15,
    played: 12,
    won: 4,
    drawn: 3,
    lost: 5,
    goalsFor: 7,
    goalsAgainst: 8,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 12,
    name: "ＳＣ相模原",
    rank: 12,
    points: 14,
    played: 12,
    won: 3,
    drawn: 5,
    lost: 4,
    goalsFor: 10,
    goalsAgainst: 14,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 13,
    name: "カマタマーレ讃岐",
    rank: 13,
    points: 13,
    played: 12,
    won: 3,
    drawn: 4,
    lost: 5,
    goalsFor: 10,
    goalsAgainst: 12,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 14,
    name: "ザスパ群馬",
    rank: 14,
    points: 13,
    played: 12,
    won: 3,
    drawn: 4,
    lost: 5,
    goalsFor: 18,
    goalsAgainst: 21,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 15,
    name: "高知ユナイテッドＳＣ",
    rank: 15,
    points: 12,
    played: 12,
    won: 3,
    drawn: 3,
    lost: 6,
    goalsFor: 19,
    goalsAgainst: 23,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 16,
    name: "ＡＣ長野パルセイロ",
    rank: 16,
    points: 11,
    played: 11,
    won: 3,
    drawn: 2,
    lost: 6,
    goalsFor: 11,
    goalsAgainst: 16,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 17,
    name: "ＦＣ琉球",
    rank: 17,
    points: 10,
    played: 11,
    won: 2,
    drawn: 4,
    lost: 5,
    goalsFor: 8,
    goalsAgainst: 11,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 18,
    name: "ＦＣ岐阜",
    rank: 18,
    points: 10,
    played: 11,
    won: 2,
    drawn: 4,
    lost: 5,
    goalsFor: 11,
    goalsAgainst: 16,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 19,
    name: "ガイナーレ鳥取",
    rank: 19,
    points: 10,
    played: 12,
    won: 2,
    drawn: 4,
    lost: 6,
    goalsFor: 8,
    goalsAgainst: 14,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 20,
    name: "アスルクラロ沼津",
    rank: 20,
    points: 9,
    played: 11,
    won: 1,
    drawn: 6,
    lost: 4,
    goalsFor: 8,
    goalsAgainst: 10,
    logo: "/placeholder.svg?height=24&width=24",
  },
];

export const U15A: SoccerTeam[] = [
  {
    id: 1,
    name: "ツエーゲン金沢(石川)",
    rank: 1,
    points: 24,
    played: 8,
    won: 8,
    drawn: 0,
    lost: 0,
    goalsFor: 29,
    goalsAgainst: 3,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 2,
    name: "松本山雅FC(長野)",
    rank: 2,
    points: 21,
    played: 8,
    won: 7,
    drawn: 0,
    lost: 1,
    goalsFor: 31,
    goalsAgainst: 7,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 3,
    name: "カターレ富山(富山)",
    rank: 3,
    points: 21,
    played: 8,
    won: 7,
    drawn: 0,
    lost: 1,
    goalsFor: 28,
    goalsAgainst: 5,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 4,
    name: "アルビレックス新潟(新潟)",
    rank: 4,
    points: 19,
    played: 8,
    won: 6,
    drawn: 1,
    lost: 1,
    goalsFor: 20,
    goalsAgainst: 6,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 5,
    name: "PateoFC金沢(石川)",
    rank: 5,
    points: 15,
    played: 8,
    won: 5,
    drawn: 0,
    lost: 3,
    goalsFor: 33,
    goalsAgainst: 11,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 6,
    name: "長岡JYFC(新潟)",
    rank: 6,
    points: 14,
    played: 8,
    won: 4,
    drawn: 2,
    lost: 2,
    goalsFor: 16,
    goalsAgainst: 14,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 7,
    name: "AC長野パルセイロ(長野)",
    rank: 7,
    points: 9,
    played: 8,
    won: 3,
    drawn: 0,
    lost: 5,
    goalsFor: 19,
    goalsAgainst: 17,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 8,
    name: "SQUARE富山(富山)",
    rank: 8,
    points: 9,
    played: 8,
    won: 3,
    drawn: 0,
    lost: 5,
    goalsFor: 11,
    goalsAgainst: 20,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 9,
    name: "グランセナ新潟(新潟)",
    rank: 9,
    points: 7,
    played: 8,
    won: 2,
    drawn: 1,
    lost: 5,
    goalsFor: 6,
    goalsAgainst: 14,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 10,
    name: "坂井ph丸岡JY(福井)",
    rank: 10,
    points: 3,
    played: 8,
    won: 1,
    drawn: 0,
    lost: 7,
    goalsFor: 4,
    goalsAgainst: 19,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 11,
    name: "F.C.CEDAC(長野)",
    rank: 11,
    points: 0,
    played: 8,
    won: 0,
    drawn: 0,
    lost: 8,
    goalsFor: 2,
    goalsAgainst: 22,
    logo: "/placeholder.svg?height=24&width=24",
  },
  {
    id: 12,
    name: "F.THREE(新潟)",
    rank: 12,
    points: 0,
    played: 8,
    won: 0,
    drawn: 0,
    lost: 8,
    goalsFor: 1,
    goalsAgainst: 62,
    logo: "/placeholder.svg?height=24&width=24",
  },
];
export const U13 = [
  {
    id: 1,
    name: "ツエーゲン金沢(石川)",
    rank: 1,
    points: 6,
    played: 2,
    won: 2,
    drawn: 0,
    lost: 0,
    goalsFor: 13,
    goalsAgainst: 0,
    goalDifference: 13,
  },
  {
    id: 2,
    name: "松本山雅FC(長野)",
    rank: 2,
    points: 6,
    played: 2,
    won: 2,
    drawn: 0,
    lost: 0,
    goalsFor: 6,
    goalsAgainst: 1,
    goalDifference: 5,
  },
  {
    id: 3,
    name: "アルビレックス新潟(新潟)",
    rank: 3,
    points: 6,
    played: 2,
    won: 2,
    drawn: 0,
    lost: 0,
    goalsFor: 6,
    goalsAgainst: 2,
    goalDifference: 4,
  },
  {
    id: 4,
    name: "PateoFC金沢(石川)",
    rank: 4,
    points: 6,
    played: 2,
    won: 2,
    drawn: 0,
    lost: 0,
    goalsFor: 3,
    goalsAgainst: 1,
    goalDifference: 2,
  },
  {
    id: 5,
    name: "FC 北 陸(石川)",
    rank: 5,
    points: 3,
    played: 2,
    won: 1,
    drawn: 0,
    lost: 1,
    goalsFor: 2,
    goalsAgainst: 6,
    goalDifference: -4,
  },
  {
    id: 6,
    name: "エスポワール白山(石川)",
    rank: 6,
    points: 1,
    played: 2,
    won: 0,
    drawn: 1,
    lost: 1,
    goalsFor: 1,
    goalsAgainst: 2,
    goalDifference: -1,
  },
  {
    id: 7,
    name: "カターレ富山(富山)",
    rank: 7,
    points: 1,
    played: 2,
    won: 0,
    drawn: 1,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 2,
    goalDifference: -2,
  },
  {
    id: 8,
    name: "長岡JYFC(新潟)",
    rank: 8,
    points: 0,
    played: 2,
    won: 0,
    drawn: 0,
    lost: 2,
    goalsFor: 1,
    goalsAgainst: 4,
    goalDifference: -3,
  },
  {
    id: 9,
    name: "F.C.CEDAC(長野)",
    rank: 9,
    points: 0,
    played: 2,
    won: 0,
    drawn: 0,
    lost: 2,
    goalsFor: 2,
    goalsAgainst: 8,
    goalDifference: -6,
  },
  {
    id: 10,
    name: "FC社南マリーナ(福井)",
    rank: 10,
    points: 0,
    played: 2,
    won: 0,
    drawn: 0,
    lost: 2,
    goalsFor: 0,
    goalsAgainst: 8,
    goalDifference: -8,
  },
];

export const U14 = [
  {
    id: 1,
    name: "松本山雅FC",
    rank: 1,
    points: 3,
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    goalsFor: 3,
    goalsAgainst: 0,
    goalDifference: 3,
  },
  {
    id: 2,
    name: "アルビレックス新潟",
    rank: 2,
    points: 0,
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
  },
  {
    id: 3,
    name: "カターレ富山",
    rank: 2,
    points: 0,
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
  },
  {
    id: 4,
    name: "ツエーゲン金沢",
    rank: 2,
    points: 0,
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    goalDifference: 0,
  },
  {
    id: 5,
    name: "AC長野パルセイロ",
    rank: 5,
    points: 0,
    played: 1,
    won: 0,
    drawn: 0,
    lost: 1,
    goalsFor: 0,
    goalsAgainst: 3,
    goalDifference: -3,
  },
];

export const U15B = [
  {
    id: 1,
    name: "フォルツァ松本",
    rank: 1,
    points: 12,
    played: 9,
    won: 4,
    drawn: 0,
    lost: 5,
    goalsFor: 17,
    goalsAgainst: 1,
    goalDifference: 16,
  },
  {
    id: 2,
    name: "アルティスタ浅間",
    rank: 2,
    points: 10,
    played: 9,
    won: 3,
    drawn: 1,
    lost: 5,
    goalsFor: 12,
    goalsAgainst: 2,
    goalDifference: 10,
  },
  {
    id: 3,
    name: "Laule FC",
    rank: 3,
    points: 8,
    played: 9,
    won: 2,
    drawn: 2,
    lost: 5,
    goalsFor: 12,
    goalsAgainst: 4,
    goalDifference: 8,
  },
  {
    id: 4,
    name: "FC ASA FUTURO",
    rank: 4,
    points: 8,
    played: 9,
    won: 2,
    drawn: 2,
    lost: 5,
    goalsFor: 9,
    goalsAgainst: 5,
    goalDifference: 4,
  },
  {
    id: 5,
    name: "松本山雅FC 上伊那",
    rank: 5,
    points: 6,
    played: 9,
    won: 2,
    drawn: 0,
    lost: 7,
    goalsFor: 11,
    goalsAgainst: 9,
    goalDifference: 2,
  },
  {
    id: 6,
    name: "アンテロープ塩尻",
    rank: 6,
    points: 4,
    played: 9,
    won: 1,
    drawn: 1,
    lost: 7,
    goalsFor: 5,
    goalsAgainst: 9,
    goalDifference: -4,
  },
  {
    id: 7,
    name: "松本山雅FC B",
    rank: 7,
    points: 3,
    played: 9,
    won: 1,
    drawn: 0,
    lost: 8,
    goalsFor: 5,
    goalsAgainst: 11,
    goalDifference: -6,
  },
  {
    id: 8,
    name: "C.F. BARRO",
    rank: 8,
    points: 3,
    played: 9,
    won: 1,
    drawn: 0,
    lost: 8,
    goalsFor: 4,
    goalsAgainst: 12,
    goalDifference: -8,
  },
  {
    id: 9,
    name: "LIGARE上田",
    rank: 9,
    points: 2,
    played: 9,
    won: 0,
    drawn: 2,
    lost: 7,
    goalsFor: 3,
    goalsAgainst: 10,
    goalDifference: -7,
  },
  {
    id: 10,
    name: "アザリー飯田",
    rank: 10,
    points: 0,
    played: 9,
    won: 0,
    drawn: 0,
    lost: 9,
    goalsFor: 5,
    goalsAgainst: 20,
    goalDifference: -15,
  },
];

export const U18B = [
  {
    id: 1,
    name: "松本山雅U18 2nd",
    rank: 1,
    points: 7,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    goalsFor: 13,
    goalsAgainst: 3,
    goalDifference: 10,
  },
  {
    id: 2,
    name: "上田西2nd",
    rank: 1,
    points: 7,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    goalsFor: 7,
    goalsAgainst: 3,
    goalDifference: 4,
  },
  {
    id: 3,
    name: "長野吉田",
    rank: 1,
    points: 7,
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    goalsFor: 9,
    goalsAgainst: 2,
    goalDifference: 7,
  },
  {
    id: 4,
    name: "松本第一2nd",
    rank: 4,
    points: 6,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    goalsFor: 13,
    goalsAgainst: 3,
    goalDifference: 10,
  },
  {
    id: 5,
    name: "赤穂",
    rank: 4,
    points: 6,
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
  },
  {
    id: 6,
    name: "都市大塩尻2nd",
    rank: 6,
    points: 1,
    played: 3,
    won: 0,
    drawn: 1,
    lost: 2,
    goalsFor: 3,
    goalsAgainst: 6,
    goalDifference: -3,
  },
  {
    id: 7,
    name: "長野日大2nd",
    rank: 7,
    points: 0,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    goalsFor: 0,
    goalsAgainst: 9,
    goalDifference: -9,
  },
  {
    id: 8,
    name: "伊那北",
    rank: 7,
    points: 0,
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    goalsFor: 1,
    goalsAgainst: 18,
    goalDifference: -17,
  },
];
